### ISSUE TITLE
Installation might require some extra packages?

### ISSUE THREAD

**Issue by jtrim-ons** [co-analysis/a11ytables#99]
I'm not super-experienced with R package installation, but just sharing my experience in case it's helpful. I tried installing a11ytables yesterday on a machine that didn't have things like tibble and knitr installed, and it was failing with error messages.

When I installed tidyverse and retried, everything was fine.

It's probably a bit of a non-issue (pretty much everyone has tidyverse installed?) or maybe something weird with my R setup, but I thought I'd mention it just in case it's helpful. Feel free to close.

**Comment by matt-dray** [comment]
Well spotted! Basically, {a11ytables} only depends on two packages: {pillar} and {openxlsx}. these are both installed when running `remotes::install_github("a11ytables", build_vignettes = TRUE)`, as instructed in the README. 

However, you also need some extra packages when building the vignettes (e.g. one of the vignettes requires the {tibble} package). As a result, I've changed the README instruction to include the argument `dependencies = TRUE` in `install_github()`. This installs the required packages {pillar} and {openxlsx} _plus_ the packages listed under 'Suggests' in [the DESCRIPTION file](https://github.com/co-analysis/a11ytables/blob/main/DESCRIPTION).

Other users may not have seen your error because, as you say, they already had these 'Suggested' packages installed on their machines. This is a good lesson for me about testing package installation on a clean system! Cheers.

**Comment by jtrim-ons** [comment]
Thank you!
